// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package cli

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Hello: %s": 1,
	"i18n":      0,
}

var enIndex = []uint32{ // 3 elements
	0x00000000, 0x00000005, 0x00000012,
} // Size: 36 bytes

const enData string = "\x02i18n\x02Hello: %[1]s"

var zhIndex = []uint32{ // 3 elements
	0x00000000, 0x0000000a, 0x00000018,
} // Size: 36 bytes

const zhData string = "\x02国际化\x02您好: %[1]s"

// Total table size 114 bytes (0KiB); checksum: 262FC1A6
